dbfilename redis_queue.rdb
dir /home/lahoussine/Plateform_B2B_V4/frappe-bench/config/pids
pidfile /home/lahoussine/Plateform_B2B_V4/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/lahoussine/Plateform_B2B_V4/frappe-bench/config/redis_queue.acl
