/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AgencesRouteImport } from './routes/agences'
import { Route as AideRouteImport } from './routes/aide'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CarrieresRouteImport } from './routes/carrieres'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as DevenirPartenaireRouteImport } from './routes/devenir-partenaire'
import { Route as EtudesRouteImport } from './routes/etudes'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as InscriptionAgenceRouteImport } from './routes/inscription-agence'
import { Route as InscriptionClientRouteImport } from './routes/inscription-client'
import { Route as PostulerUnProjetRouteImport } from './routes/postuler-un-projet'
import { Route as PresseRouteImport } from './routes/presse'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AgencesIdRouteImport } from './routes/agences_.$id'
import { Route as FonctionnalitesSlugRouteImport } from './routes/fonctionnalites.$slug'
import { Route as ProjetsIdRouteImport } from './routes/projets_.$id'
import { Route as AuthenticatedAdminAvisRouteImport } from './routes/_authenticated/admin.avis'
import { Route as AuthenticatedAdminLitigesRouteImport } from './routes/_authenticated/admin.litiges'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminTableauDeBordRouteImport } from './routes/_authenticated/admin.tableau-de-bord'
import { Route as AuthenticatedAgenceAnalyticsRouteImport } from './routes/_authenticated/agence.analytics'
import { Route as AuthenticatedAgenceFacturationRouteImport } from './routes/_authenticated/agence.facturation'
import { Route as AuthenticatedAgenceInvitationsRouteImport } from './routes/_authenticated/agence.invitations'
import { Route as AuthenticatedAgenceMesProspectionsRouteImport } from './routes/_authenticated/agence.mes-prospections'
import { Route as AuthenticatedAgenceNotificationsRouteImport } from './routes/_authenticated/agence.notifications'
import { Route as AuthenticatedAgenceOpportunitesRouteImport } from './routes/_authenticated/agence.opportunites'
import { Route as AuthenticatedAgenceParametresRouteImport } from './routes/_authenticated/agence.parametres'
import { Route as AuthenticatedAgenceProfilRouteImport } from './routes/_authenticated/agence.profil'
import { Route as AuthenticatedAgenceProjetsEnCoursRouteImport } from './routes/_authenticated/agence.projets-en-cours'
import { Route as AuthenticatedAgenceProspectionRouteImport } from './routes/_authenticated/agence.prospection'
import { Route as AuthenticatedAgenceSuspensionRouteImport } from './routes/_authenticated/agence.suspension'
import { Route as AuthenticatedAgenceTableauDeBordRouteImport } from './routes/_authenticated/agence.tableau-de-bord'
import { Route as AuthenticatedAgenceWorkflowRouteImport } from './routes/_authenticated/agence.workflow'
import { Route as AuthenticatedClientAgencesFavoritesRouteImport } from './routes/_authenticated/client.agences-favorites'
import { Route as AuthenticatedClientCollaborationsRouteImport } from './routes/_authenticated/client.collaborations'
import { Route as AuthenticatedClientMesProjetsRouteImport } from './routes/_authenticated/client.mes-projets'
import { Route as AuthenticatedClientMonProfilRouteImport } from './routes/_authenticated/client.mon-profil'
import { Route as AuthenticatedClientNotificationsRouteImport } from './routes/_authenticated/client.notifications'
import { Route as AuthenticatedClientParametresRouteImport } from './routes/_authenticated/client.parametres'
import { Route as AuthenticatedClientPostulerUnProjetRouteImport } from './routes/_authenticated/client.postuler-un-projet'
import { Route as AuthenticatedClientTableauDeBordRouteImport } from './routes/_authenticated/client.tableau-de-bord'
import { Route as AuthenticatedClientMesProjetsIdRouteImport } from './routes/_authenticated/client.mes-projets_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const ProjetsIdRoute = ProjetsIdRouteImport.update({
  id: '/projets_/$id',
  path: '/projets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencesRoute = AgencesRouteImport.update({
  id: '/agences',
  path: '/agences',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrieresRoute = CarrieresRouteImport.update({
  id: '/carrieres',
  path: '/carrieres',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirPartenaireRoute = DevenirPartenaireRouteImport.update({
  id: '/devenir-partenaire',
  path: '/devenir-partenaire',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudesRoute = EtudesRouteImport.update({
  id: '/etudes',
  path: '/etudes',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionAgenceRoute = InscriptionAgenceRouteImport.update({
  id: '/inscription-agence',
  path: '/inscription-agence',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionClientRoute = InscriptionClientRouteImport.update({
  id: '/inscription-client',
  path: '/inscription-client',
  getParentRoute: () => rootRouteImport,
} as any)
const PostulerUnProjetRoute = PostulerUnProjetRouteImport.update({
  id: '/postuler-un-projet',
  path: '/postuler-un-projet',
  getParentRoute: () => rootRouteImport,
} as any)
const PresseRoute = PresseRouteImport.update({
  id: '/presse',
  path: '/presse',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencesIdRoute = AgencesIdRouteImport.update({
  id: '/agences_/$id',
  path: '/agences/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnalitesSlugRoute = FonctionnalitesSlugRouteImport.update({
  id: '/fonctionnalites/$slug',
  path: '/fonctionnalites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAvisRoute = AuthenticatedAdminAvisRouteImport.update({
  id: '/admin/avis',
  path: '/admin/avis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLitigesRoute =
  AuthenticatedAdminLitigesRouteImport.update({
    id: '/admin/litiges',
    path: '/admin/litiges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTableauDeBordRoute =
  AuthenticatedAdminTableauDeBordRouteImport.update({
    id: '/admin/tableau-de-bord',
    path: '/admin/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceAnalyticsRoute =
  AuthenticatedAgenceAnalyticsRouteImport.update({
    id: '/agence/analytics',
    path: '/agence/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceFacturationRoute =
  AuthenticatedAgenceFacturationRouteImport.update({
    id: '/agence/facturation',
    path: '/agence/facturation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceInvitationsRoute =
  AuthenticatedAgenceInvitationsRouteImport.update({
    id: '/agence/invitations',
    path: '/agence/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceMesProspectionsRoute =
  AuthenticatedAgenceMesProspectionsRouteImport.update({
    id: '/agence/mes-prospections',
    path: '/agence/mes-prospections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceNotificationsRoute =
  AuthenticatedAgenceNotificationsRouteImport.update({
    id: '/agence/notifications',
    path: '/agence/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceOpportunitesRoute =
  AuthenticatedAgenceOpportunitesRouteImport.update({
    id: '/agence/opportunites',
    path: '/agence/opportunites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceParametresRoute =
  AuthenticatedAgenceParametresRouteImport.update({
    id: '/agence/parametres',
    path: '/agence/parametres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceProfilRoute =
  AuthenticatedAgenceProfilRouteImport.update({
    id: '/agence/profil',
    path: '/agence/profil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceProjetsEnCoursRoute =
  AuthenticatedAgenceProjetsEnCoursRouteImport.update({
    id: '/agence/projets-en-cours',
    path: '/agence/projets-en-cours',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceProspectionRoute =
  AuthenticatedAgenceProspectionRouteImport.update({
    id: '/agence/prospection',
    path: '/agence/prospection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceSuspensionRoute =
  AuthenticatedAgenceSuspensionRouteImport.update({
    id: '/agence/suspension',
    path: '/agence/suspension',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceTableauDeBordRoute =
  AuthenticatedAgenceTableauDeBordRouteImport.update({
    id: '/agence/tableau-de-bord',
    path: '/agence/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenceWorkflowRoute =
  AuthenticatedAgenceWorkflowRouteImport.update({
    id: '/agence/workflow',
    path: '/agence/workflow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientAgencesFavoritesRoute =
  AuthenticatedClientAgencesFavoritesRouteImport.update({
    id: '/client/agences-favorites',
    path: '/client/agences-favorites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientCollaborationsRoute =
  AuthenticatedClientCollaborationsRouteImport.update({
    id: '/client/collaborations',
    path: '/client/collaborations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientMesProjetsRoute =
  AuthenticatedClientMesProjetsRouteImport.update({
    id: '/client/mes-projets',
    path: '/client/mes-projets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientMonProfilRoute =
  AuthenticatedClientMonProfilRouteImport.update({
    id: '/client/mon-profil',
    path: '/client/mon-profil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientNotificationsRoute =
  AuthenticatedClientNotificationsRouteImport.update({
    id: '/client/notifications',
    path: '/client/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientParametresRoute =
  AuthenticatedClientParametresRouteImport.update({
    id: '/client/parametres',
    path: '/client/parametres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientPostulerUnProjetRoute =
  AuthenticatedClientPostulerUnProjetRouteImport.update({
    id: '/client/postuler-un-projet',
    path: '/client/postuler-un-projet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientTableauDeBordRoute =
  AuthenticatedClientTableauDeBordRouteImport.update({
    id: '/client/tableau-de-bord',
    path: '/client/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientMesProjetsIdRoute =
  AuthenticatedClientMesProjetsIdRouteImport.update({
    id: '/client/mes-projets_/$id',
    path: '/client/mes-projets/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/agences': typeof AgencesRoute
  '/aide': typeof AideRoute
  '/blog': typeof BlogRoute
  '/carrieres': typeof CarrieresRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/devenir-partenaire': typeof DevenirPartenaireRoute
  '/etudes': typeof EtudesRoute
  '/guides': typeof GuidesRoute
  '/inscription-agence': typeof InscriptionAgenceRoute
  '/inscription-client': typeof InscriptionClientRoute
  '/postuler-un-projet': typeof PostulerUnProjetRoute
  '/presse': typeof PresseRoute
  '/projets': typeof ProjetsRoute
  '/ressources': typeof RessourcesRoute
  '/services': typeof ServicesRoute
  '/tarifs': typeof TarifsRoute
  '/agences/$id': typeof AgencesIdRoute
  '/fonctionnalites/$slug': typeof FonctionnalitesSlugRoute
  '/projets/$id': typeof ProjetsIdRoute
  '/admin/avis': typeof AuthenticatedAdminAvisRoute
  '/admin/litiges': typeof AuthenticatedAdminLitigesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/tableau-de-bord': typeof AuthenticatedAdminTableauDeBordRoute
  '/agence/analytics': typeof AuthenticatedAgenceAnalyticsRoute
  '/agence/facturation': typeof AuthenticatedAgenceFacturationRoute
  '/agence/invitations': typeof AuthenticatedAgenceInvitationsRoute
  '/agence/mes-prospections': typeof AuthenticatedAgenceMesProspectionsRoute
  '/agence/notifications': typeof AuthenticatedAgenceNotificationsRoute
  '/agence/opportunites': typeof AuthenticatedAgenceOpportunitesRoute
  '/agence/parametres': typeof AuthenticatedAgenceParametresRoute
  '/agence/profil': typeof AuthenticatedAgenceProfilRoute
  '/agence/projets-en-cours': typeof AuthenticatedAgenceProjetsEnCoursRoute
  '/agence/prospection': typeof AuthenticatedAgenceProspectionRoute
  '/agence/suspension': typeof AuthenticatedAgenceSuspensionRoute
  '/agence/tableau-de-bord': typeof AuthenticatedAgenceTableauDeBordRoute
  '/agence/workflow': typeof AuthenticatedAgenceWorkflowRoute
  '/client/agences-favorites': typeof AuthenticatedClientAgencesFavoritesRoute
  '/client/collaborations': typeof AuthenticatedClientCollaborationsRoute
  '/client/mes-projets': typeof AuthenticatedClientMesProjetsRoute
  '/client/mon-profil': typeof AuthenticatedClientMonProfilRoute
  '/client/notifications': typeof AuthenticatedClientNotificationsRoute
  '/client/parametres': typeof AuthenticatedClientParametresRoute
  '/client/postuler-un-projet': typeof AuthenticatedClientPostulerUnProjetRoute
  '/client/tableau-de-bord': typeof AuthenticatedClientTableauDeBordRoute
  '/client/mes-projets/$id': typeof AuthenticatedClientMesProjetsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/agences': typeof AgencesRoute
  '/aide': typeof AideRoute
  '/blog': typeof BlogRoute
  '/carrieres': typeof CarrieresRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/devenir-partenaire': typeof DevenirPartenaireRoute
  '/etudes': typeof EtudesRoute
  '/guides': typeof GuidesRoute
  '/inscription-agence': typeof InscriptionAgenceRoute
  '/inscription-client': typeof InscriptionClientRoute
  '/postuler-un-projet': typeof PostulerUnProjetRoute
  '/presse': typeof PresseRoute
  '/projets': typeof ProjetsRoute
  '/ressources': typeof RessourcesRoute
  '/services': typeof ServicesRoute
  '/tarifs': typeof TarifsRoute
  '/agences/$id': typeof AgencesIdRoute
  '/fonctionnalites/$slug': typeof FonctionnalitesSlugRoute
  '/projets/$id': typeof ProjetsIdRoute
  '/admin/avis': typeof AuthenticatedAdminAvisRoute
  '/admin/litiges': typeof AuthenticatedAdminLitigesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/tableau-de-bord': typeof AuthenticatedAdminTableauDeBordRoute
  '/agence/analytics': typeof AuthenticatedAgenceAnalyticsRoute
  '/agence/facturation': typeof AuthenticatedAgenceFacturationRoute
  '/agence/invitations': typeof AuthenticatedAgenceInvitationsRoute
  '/agence/mes-prospections': typeof AuthenticatedAgenceMesProspectionsRoute
  '/agence/notifications': typeof AuthenticatedAgenceNotificationsRoute
  '/agence/opportunites': typeof AuthenticatedAgenceOpportunitesRoute
  '/agence/parametres': typeof AuthenticatedAgenceParametresRoute
  '/agence/profil': typeof AuthenticatedAgenceProfilRoute
  '/agence/projets-en-cours': typeof AuthenticatedAgenceProjetsEnCoursRoute
  '/agence/prospection': typeof AuthenticatedAgenceProspectionRoute
  '/agence/suspension': typeof AuthenticatedAgenceSuspensionRoute
  '/agence/tableau-de-bord': typeof AuthenticatedAgenceTableauDeBordRoute
  '/agence/workflow': typeof AuthenticatedAgenceWorkflowRoute
  '/client/agences-favorites': typeof AuthenticatedClientAgencesFavoritesRoute
  '/client/collaborations': typeof AuthenticatedClientCollaborationsRoute
  '/client/mes-projets': typeof AuthenticatedClientMesProjetsRoute
  '/client/mon-profil': typeof AuthenticatedClientMonProfilRoute
  '/client/notifications': typeof AuthenticatedClientNotificationsRoute
  '/client/parametres': typeof AuthenticatedClientParametresRoute
  '/client/postuler-un-projet': typeof AuthenticatedClientPostulerUnProjetRoute
  '/client/tableau-de-bord': typeof AuthenticatedClientTableauDeBordRoute
  '/client/mes-projets/$id': typeof AuthenticatedClientMesProjetsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/agences': typeof AgencesRoute
  '/aide': typeof AideRoute
  '/blog': typeof BlogRoute
  '/carrieres': typeof CarrieresRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/devenir-partenaire': typeof DevenirPartenaireRoute
  '/etudes': typeof EtudesRoute
  '/guides': typeof GuidesRoute
  '/inscription-agence': typeof InscriptionAgenceRoute
  '/inscription-client': typeof InscriptionClientRoute
  '/postuler-un-projet': typeof PostulerUnProjetRoute
  '/presse': typeof PresseRoute
  '/projets': typeof ProjetsRoute
  '/ressources': typeof RessourcesRoute
  '/services': typeof ServicesRoute
  '/tarifs': typeof TarifsRoute
  '/agences_/$id': typeof AgencesIdRoute
  '/fonctionnalites/$slug': typeof FonctionnalitesSlugRoute
  '/projets_/$id': typeof ProjetsIdRoute
  '/_authenticated/admin/avis': typeof AuthenticatedAdminAvisRoute
  '/_authenticated/admin/litiges': typeof AuthenticatedAdminLitigesRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/tableau-de-bord': typeof AuthenticatedAdminTableauDeBordRoute
  '/_authenticated/agence/analytics': typeof AuthenticatedAgenceAnalyticsRoute
  '/_authenticated/agence/facturation': typeof AuthenticatedAgenceFacturationRoute
  '/_authenticated/agence/invitations': typeof AuthenticatedAgenceInvitationsRoute
  '/_authenticated/agence/mes-prospections': typeof AuthenticatedAgenceMesProspectionsRoute
  '/_authenticated/agence/notifications': typeof AuthenticatedAgenceNotificationsRoute
  '/_authenticated/agence/opportunites': typeof AuthenticatedAgenceOpportunitesRoute
  '/_authenticated/agence/parametres': typeof AuthenticatedAgenceParametresRoute
  '/_authenticated/agence/profil': typeof AuthenticatedAgenceProfilRoute
  '/_authenticated/agence/projets-en-cours': typeof AuthenticatedAgenceProjetsEnCoursRoute
  '/_authenticated/agence/prospection': typeof AuthenticatedAgenceProspectionRoute
  '/_authenticated/agence/suspension': typeof AuthenticatedAgenceSuspensionRoute
  '/_authenticated/agence/tableau-de-bord': typeof AuthenticatedAgenceTableauDeBordRoute
  '/_authenticated/agence/workflow': typeof AuthenticatedAgenceWorkflowRoute
  '/_authenticated/client/agences-favorites': typeof AuthenticatedClientAgencesFavoritesRoute
  '/_authenticated/client/collaborations': typeof AuthenticatedClientCollaborationsRoute
  '/_authenticated/client/mes-projets': typeof AuthenticatedClientMesProjetsRoute
  '/_authenticated/client/mon-profil': typeof AuthenticatedClientMonProfilRoute
  '/_authenticated/client/notifications': typeof AuthenticatedClientNotificationsRoute
  '/_authenticated/client/parametres': typeof AuthenticatedClientParametresRoute
  '/_authenticated/client/postuler-un-projet': typeof AuthenticatedClientPostulerUnProjetRoute
  '/_authenticated/client/tableau-de-bord': typeof AuthenticatedClientTableauDeBordRoute
  '/_authenticated/client/mes-projets_/$id': typeof AuthenticatedClientMesProjetsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/agences'
    | '/aide'
    | '/blog'
    | '/carrieres'
    | '/comment-ca-marche'
    | '/connexion'
    | '/devenir-partenaire'
    | '/etudes'
    | '/guides'
    | '/inscription-agence'
    | '/inscription-client'
    | '/postuler-un-projet'
    | '/presse'
    | '/projets'
    | '/ressources'
    | '/services'
    | '/tarifs'
    | '/agences/$id'
    | '/fonctionnalites/$slug'
    | '/projets/$id'
    | '/admin/avis'
    | '/admin/litiges'
    | '/admin/notifications'
    | '/admin/tableau-de-bord'
    | '/agence/analytics'
    | '/agence/facturation'
    | '/agence/invitations'
    | '/agence/mes-prospections'
    | '/agence/notifications'
    | '/agence/opportunites'
    | '/agence/parametres'
    | '/agence/profil'
    | '/agence/projets-en-cours'
    | '/agence/prospection'
    | '/agence/suspension'
    | '/agence/tableau-de-bord'
    | '/agence/workflow'
    | '/client/agences-favorites'
    | '/client/collaborations'
    | '/client/mes-projets'
    | '/client/mon-profil'
    | '/client/notifications'
    | '/client/parametres'
    | '/client/postuler-un-projet'
    | '/client/tableau-de-bord'
    | '/client/mes-projets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/agences'
    | '/aide'
    | '/blog'
    | '/carrieres'
    | '/comment-ca-marche'
    | '/connexion'
    | '/devenir-partenaire'
    | '/etudes'
    | '/guides'
    | '/inscription-agence'
    | '/inscription-client'
    | '/postuler-un-projet'
    | '/presse'
    | '/projets'
    | '/ressources'
    | '/services'
    | '/tarifs'
    | '/agences/$id'
    | '/fonctionnalites/$slug'
    | '/projets/$id'
    | '/admin/avis'
    | '/admin/litiges'
    | '/admin/notifications'
    | '/admin/tableau-de-bord'
    | '/agence/analytics'
    | '/agence/facturation'
    | '/agence/invitations'
    | '/agence/mes-prospections'
    | '/agence/notifications'
    | '/agence/opportunites'
    | '/agence/parametres'
    | '/agence/profil'
    | '/agence/projets-en-cours'
    | '/agence/prospection'
    | '/agence/suspension'
    | '/agence/tableau-de-bord'
    | '/agence/workflow'
    | '/client/agences-favorites'
    | '/client/collaborations'
    | '/client/mes-projets'
    | '/client/mon-profil'
    | '/client/notifications'
    | '/client/parametres'
    | '/client/postuler-un-projet'
    | '/client/tableau-de-bord'
    | '/client/mes-projets/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/agences'
    | '/aide'
    | '/blog'
    | '/carrieres'
    | '/comment-ca-marche'
    | '/connexion'
    | '/devenir-partenaire'
    | '/etudes'
    | '/guides'
    | '/inscription-agence'
    | '/inscription-client'
    | '/postuler-un-projet'
    | '/presse'
    | '/projets'
    | '/ressources'
    | '/services'
    | '/tarifs'
    | '/agences_/$id'
    | '/fonctionnalites/$slug'
    | '/projets_/$id'
    | '/_authenticated/admin/avis'
    | '/_authenticated/admin/litiges'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/tableau-de-bord'
    | '/_authenticated/agence/analytics'
    | '/_authenticated/agence/facturation'
    | '/_authenticated/agence/invitations'
    | '/_authenticated/agence/mes-prospections'
    | '/_authenticated/agence/notifications'
    | '/_authenticated/agence/opportunites'
    | '/_authenticated/agence/parametres'
    | '/_authenticated/agence/profil'
    | '/_authenticated/agence/projets-en-cours'
    | '/_authenticated/agence/prospection'
    | '/_authenticated/agence/suspension'
    | '/_authenticated/agence/tableau-de-bord'
    | '/_authenticated/agence/workflow'
    | '/_authenticated/client/agences-favorites'
    | '/_authenticated/client/collaborations'
    | '/_authenticated/client/mes-projets'
    | '/_authenticated/client/mon-profil'
    | '/_authenticated/client/notifications'
    | '/_authenticated/client/parametres'
    | '/_authenticated/client/postuler-un-projet'
    | '/_authenticated/client/tableau-de-bord'
    | '/_authenticated/client/mes-projets_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AgencesRoute: typeof AgencesRoute
  AideRoute: typeof AideRoute
  BlogRoute: typeof BlogRoute
  CarrieresRoute: typeof CarrieresRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ConnexionRoute: typeof ConnexionRoute
  DevenirPartenaireRoute: typeof DevenirPartenaireRoute
  EtudesRoute: typeof EtudesRoute
  GuidesRoute: typeof GuidesRoute
  InscriptionAgenceRoute: typeof InscriptionAgenceRoute
  InscriptionClientRoute: typeof InscriptionClientRoute
  PostulerUnProjetRoute: typeof PostulerUnProjetRoute
  PresseRoute: typeof PresseRoute
  ProjetsRoute: typeof ProjetsRoute
  RessourcesRoute: typeof RessourcesRoute
  ServicesRoute: typeof ServicesRoute
  TarifsRoute: typeof TarifsRoute
  AgencesIdRoute: typeof AgencesIdRoute
  FonctionnalitesSlugRoute: typeof FonctionnalitesSlugRoute
  ProjetsIdRoute: typeof ProjetsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agences': {
      id: '/agences'
      path: '/agences'
      fullPath: '/agences'
      preLoaderRoute: typeof AgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrieres': {
      id: '/carrieres'
      path: '/carrieres'
      fullPath: '/carrieres'
      preLoaderRoute: typeof CarrieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-partenaire': {
      id: '/devenir-partenaire'
      path: '/devenir-partenaire'
      fullPath: '/devenir-partenaire'
      preLoaderRoute: typeof DevenirPartenaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudes': {
      id: '/etudes'
      path: '/etudes'
      fullPath: '/etudes'
      preLoaderRoute: typeof EtudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-agence': {
      id: '/inscription-agence'
      path: '/inscription-agence'
      fullPath: '/inscription-agence'
      preLoaderRoute: typeof InscriptionAgenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-client': {
      id: '/inscription-client'
      path: '/inscription-client'
      fullPath: '/inscription-client'
      preLoaderRoute: typeof InscriptionClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postuler-un-projet': {
      id: '/postuler-un-projet'
      path: '/postuler-un-projet'
      fullPath: '/postuler-un-projet'
      preLoaderRoute: typeof PostulerUnProjetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presse': {
      id: '/presse'
      path: '/presse'
      fullPath: '/presse'
      preLoaderRoute: typeof PresseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agences_/$id': {
      id: '/agences_/$id'
      path: '/agences/$id'
      fullPath: '/agences/$id'
      preLoaderRoute: typeof AgencesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites/$slug': {
      id: '/fonctionnalites/$slug'
      path: '/fonctionnalites/$slug'
      fullPath: '/fonctionnalites/$slug'
      preLoaderRoute: typeof FonctionnalitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets_/$id': {
      id: '/projets_/$id'
      path: '/projets/$id'
      fullPath: '/projets/$id'
      preLoaderRoute: typeof ProjetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/avis': {
      id: '/_authenticated/admin/avis'
      path: '/admin/avis'
      fullPath: '/admin/avis'
      preLoaderRoute: typeof AuthenticatedAdminAvisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/litiges': {
      id: '/_authenticated/admin/litiges'
      path: '/admin/litiges'
      fullPath: '/admin/litiges'
      preLoaderRoute: typeof AuthenticatedAdminLitigesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tableau-de-bord': {
      id: '/_authenticated/admin/tableau-de-bord'
      path: '/admin/tableau-de-bord'
      fullPath: '/admin/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedAdminTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/analytics': {
      id: '/_authenticated/agence/analytics'
      path: '/agence/analytics'
      fullPath: '/agence/analytics'
      preLoaderRoute: typeof AuthenticatedAgenceAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/facturation': {
      id: '/_authenticated/agence/facturation'
      path: '/agence/facturation'
      fullPath: '/agence/facturation'
      preLoaderRoute: typeof AuthenticatedAgenceFacturationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/invitations': {
      id: '/_authenticated/agence/invitations'
      path: '/agence/invitations'
      fullPath: '/agence/invitations'
      preLoaderRoute: typeof AuthenticatedAgenceInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/mes-prospections': {
      id: '/_authenticated/agence/mes-prospections'
      path: '/agence/mes-prospections'
      fullPath: '/agence/mes-prospections'
      preLoaderRoute: typeof AuthenticatedAgenceMesProspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/notifications': {
      id: '/_authenticated/agence/notifications'
      path: '/agence/notifications'
      fullPath: '/agence/notifications'
      preLoaderRoute: typeof AuthenticatedAgenceNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/opportunites': {
      id: '/_authenticated/agence/opportunites'
      path: '/agence/opportunites'
      fullPath: '/agence/opportunites'
      preLoaderRoute: typeof AuthenticatedAgenceOpportunitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/parametres': {
      id: '/_authenticated/agence/parametres'
      path: '/agence/parametres'
      fullPath: '/agence/parametres'
      preLoaderRoute: typeof AuthenticatedAgenceParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/profil': {
      id: '/_authenticated/agence/profil'
      path: '/agence/profil'
      fullPath: '/agence/profil'
      preLoaderRoute: typeof AuthenticatedAgenceProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/projets-en-cours': {
      id: '/_authenticated/agence/projets-en-cours'
      path: '/agence/projets-en-cours'
      fullPath: '/agence/projets-en-cours'
      preLoaderRoute: typeof AuthenticatedAgenceProjetsEnCoursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/prospection': {
      id: '/_authenticated/agence/prospection'
      path: '/agence/prospection'
      fullPath: '/agence/prospection'
      preLoaderRoute: typeof AuthenticatedAgenceProspectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/suspension': {
      id: '/_authenticated/agence/suspension'
      path: '/agence/suspension'
      fullPath: '/agence/suspension'
      preLoaderRoute: typeof AuthenticatedAgenceSuspensionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/tableau-de-bord': {
      id: '/_authenticated/agence/tableau-de-bord'
      path: '/agence/tableau-de-bord'
      fullPath: '/agence/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedAgenceTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agence/workflow': {
      id: '/_authenticated/agence/workflow'
      path: '/agence/workflow'
      fullPath: '/agence/workflow'
      preLoaderRoute: typeof AuthenticatedAgenceWorkflowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/agences-favorites': {
      id: '/_authenticated/client/agences-favorites'
      path: '/client/agences-favorites'
      fullPath: '/client/agences-favorites'
      preLoaderRoute: typeof AuthenticatedClientAgencesFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/collaborations': {
      id: '/_authenticated/client/collaborations'
      path: '/client/collaborations'
      fullPath: '/client/collaborations'
      preLoaderRoute: typeof AuthenticatedClientCollaborationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/mes-projets': {
      id: '/_authenticated/client/mes-projets'
      path: '/client/mes-projets'
      fullPath: '/client/mes-projets'
      preLoaderRoute: typeof AuthenticatedClientMesProjetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/mon-profil': {
      id: '/_authenticated/client/mon-profil'
      path: '/client/mon-profil'
      fullPath: '/client/mon-profil'
      preLoaderRoute: typeof AuthenticatedClientMonProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/notifications': {
      id: '/_authenticated/client/notifications'
      path: '/client/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof AuthenticatedClientNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/parametres': {
      id: '/_authenticated/client/parametres'
      path: '/client/parametres'
      fullPath: '/client/parametres'
      preLoaderRoute: typeof AuthenticatedClientParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/postuler-un-projet': {
      id: '/_authenticated/client/postuler-un-projet'
      path: '/client/postuler-un-projet'
      fullPath: '/client/postuler-un-projet'
      preLoaderRoute: typeof AuthenticatedClientPostulerUnProjetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/tableau-de-bord': {
      id: '/_authenticated/client/tableau-de-bord'
      path: '/client/tableau-de-bord'
      fullPath: '/client/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedClientTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/mes-projets_/$id': {
      id: '/_authenticated/client/mes-projets_/$id'
      path: '/client/mes-projets/$id'
      fullPath: '/client/mes-projets/$id'
      preLoaderRoute: typeof AuthenticatedClientMesProjetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAvisRoute: typeof AuthenticatedAdminAvisRoute
  AuthenticatedAdminLitigesRoute: typeof AuthenticatedAdminLitigesRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminTableauDeBordRoute: typeof AuthenticatedAdminTableauDeBordRoute
  AuthenticatedAgenceAnalyticsRoute: typeof AuthenticatedAgenceAnalyticsRoute
  AuthenticatedAgenceFacturationRoute: typeof AuthenticatedAgenceFacturationRoute
  AuthenticatedAgenceInvitationsRoute: typeof AuthenticatedAgenceInvitationsRoute
  AuthenticatedAgenceMesProspectionsRoute: typeof AuthenticatedAgenceMesProspectionsRoute
  AuthenticatedAgenceNotificationsRoute: typeof AuthenticatedAgenceNotificationsRoute
  AuthenticatedAgenceOpportunitesRoute: typeof AuthenticatedAgenceOpportunitesRoute
  AuthenticatedAgenceParametresRoute: typeof AuthenticatedAgenceParametresRoute
  AuthenticatedAgenceProfilRoute: typeof AuthenticatedAgenceProfilRoute
  AuthenticatedAgenceProjetsEnCoursRoute: typeof AuthenticatedAgenceProjetsEnCoursRoute
  AuthenticatedAgenceProspectionRoute: typeof AuthenticatedAgenceProspectionRoute
  AuthenticatedAgenceSuspensionRoute: typeof AuthenticatedAgenceSuspensionRoute
  AuthenticatedAgenceTableauDeBordRoute: typeof AuthenticatedAgenceTableauDeBordRoute
  AuthenticatedAgenceWorkflowRoute: typeof AuthenticatedAgenceWorkflowRoute
  AuthenticatedClientAgencesFavoritesRoute: typeof AuthenticatedClientAgencesFavoritesRoute
  AuthenticatedClientCollaborationsRoute: typeof AuthenticatedClientCollaborationsRoute
  AuthenticatedClientMesProjetsRoute: typeof AuthenticatedClientMesProjetsRoute
  AuthenticatedClientMonProfilRoute: typeof AuthenticatedClientMonProfilRoute
  AuthenticatedClientNotificationsRoute: typeof AuthenticatedClientNotificationsRoute
  AuthenticatedClientParametresRoute: typeof AuthenticatedClientParametresRoute
  AuthenticatedClientPostulerUnProjetRoute: typeof AuthenticatedClientPostulerUnProjetRoute
  AuthenticatedClientTableauDeBordRoute: typeof AuthenticatedClientTableauDeBordRoute
  AuthenticatedClientMesProjetsIdRoute: typeof AuthenticatedClientMesProjetsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAvisRoute: AuthenticatedAdminAvisRoute,
  AuthenticatedAdminLitigesRoute: AuthenticatedAdminLitigesRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminTableauDeBordRoute: AuthenticatedAdminTableauDeBordRoute,
  AuthenticatedAgenceAnalyticsRoute: AuthenticatedAgenceAnalyticsRoute,
  AuthenticatedAgenceFacturationRoute: AuthenticatedAgenceFacturationRoute,
  AuthenticatedAgenceInvitationsRoute: AuthenticatedAgenceInvitationsRoute,
  AuthenticatedAgenceMesProspectionsRoute:
  AuthenticatedAgenceMesProspectionsRoute,
  AuthenticatedAgenceNotificationsRoute: AuthenticatedAgenceNotificationsRoute,
  AuthenticatedAgenceOpportunitesRoute: AuthenticatedAgenceOpportunitesRoute,
  AuthenticatedAgenceParametresRoute: AuthenticatedAgenceParametresRoute,
  AuthenticatedAgenceProfilRoute: AuthenticatedAgenceProfilRoute,
  AuthenticatedAgenceProjetsEnCoursRoute:
  AuthenticatedAgenceProjetsEnCoursRoute,
  AuthenticatedAgenceProspectionRoute: AuthenticatedAgenceProspectionRoute,
  AuthenticatedAgenceSuspensionRoute: AuthenticatedAgenceSuspensionRoute,
  AuthenticatedAgenceTableauDeBordRoute: AuthenticatedAgenceTableauDeBordRoute,
  AuthenticatedAgenceWorkflowRoute: AuthenticatedAgenceWorkflowRoute,
  AuthenticatedClientAgencesFavoritesRoute:
  AuthenticatedClientAgencesFavoritesRoute,
  AuthenticatedClientCollaborationsRoute:
  AuthenticatedClientCollaborationsRoute,
  AuthenticatedClientMesProjetsRoute: AuthenticatedClientMesProjetsRoute,
  AuthenticatedClientMonProfilRoute: AuthenticatedClientMonProfilRoute,
  AuthenticatedClientNotificationsRoute: AuthenticatedClientNotificationsRoute,
  AuthenticatedClientParametresRoute: AuthenticatedClientParametresRoute,
  AuthenticatedClientPostulerUnProjetRoute:
  AuthenticatedClientPostulerUnProjetRoute,
  AuthenticatedClientTableauDeBordRoute: AuthenticatedClientTableauDeBordRoute,
  AuthenticatedClientMesProjetsIdRoute: AuthenticatedClientMesProjetsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AgencesRoute: AgencesRoute,
  AideRoute: AideRoute,
  BlogRoute: BlogRoute,
  CarrieresRoute: CarrieresRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ConnexionRoute: ConnexionRoute,
  DevenirPartenaireRoute: DevenirPartenaireRoute,
  EtudesRoute: EtudesRoute,
  GuidesRoute: GuidesRoute,
  InscriptionAgenceRoute: InscriptionAgenceRoute,
  InscriptionClientRoute: InscriptionClientRoute,
  PostulerUnProjetRoute: PostulerUnProjetRoute,
  PresseRoute: PresseRoute,
  ProjetsRoute: ProjetsRoute,
  RessourcesRoute: RessourcesRoute,
  ServicesRoute: ServicesRoute,
  TarifsRoute: TarifsRoute,
  AgencesIdRoute: AgencesIdRoute,
  FonctionnalitesSlugRoute: FonctionnalitesSlugRoute,
  ProjetsIdRoute: ProjetsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}