
export const SKILL_OPTIONS: string[] = [
  "SEO",
  "SEA / Google Ads",
  "Marketing digital",
  "Stratégie de contenu",
  "Réseaux sociaux",
  "Community management",
  "Growth hacking",
  "Branding",
  "Identité visuelle",
  "UX Design",
  "UI Design",
  "Copywriting",
  "Email marketing",
  "Marketing automation",
  "Web analytics",
  "Data & CRO",
  "Influence marketing",
  "Relations presse",
  "Motion design",
  "Photographie",
  "Production vidéo",
  "E-commerce",
  "ASO (App Store Optimization)",
  "Développement web",
  "Développement mobile",
  "Consulting stratégique",
];

export const TECH_STACK_OPTIONS: string[] = [
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Node.js",
  "TypeScript",
  "PHP",
  "Laravel",
  "Python",
  "Django",
  "WordPress",
  "Shopify",
  "WooCommerce",
  "Webflow",
  "Figma",
  "Adobe Creative Suite",
  "HubSpot",
  "Salesforce",
  "Google Analytics",
  "Google Tag Manager",
  "Meta Ads Manager",
  "Mailchimp",
  "AWS",
  "Google Cloud",
  "Azure",
  "Docker",
  "Flutter",
  "Swift",
  "Kotlin",
  "Go",
];

export const LANGUAGE_OPTIONS: string[] = [
  "Français",
  "Anglais",
  "Arabe",
  "Espagnol",
  "Allemand",
  "Italien",
  "Portugais",
  "Néerlandais",
  "Chinois (Mandarin)",
  "Japonais",
  "Russe",
  "Turc",
];
